import React, { useState, useMemo } from "react";
import { StepForward, RotateCcw, Terminal } from "lucide-react";
import { Tex } from "./math.jsx";

/* ============================================================
   IP DECOMPOSITION ALGORITHMS
   ISE 5406

   Three classical decomposition methods, side-by-side:

     • BENDERS DECOMPOSITION
         max  c^T x + d^T y
         s.t. A x + B y <= b,  x ∈ X (integer),  y >= 0
       Project out y → master in x with optimality / feasibility cuts
       generated by solving the dual of the y-LP at each candidate x.

     • DANTZIG-WOLFE
         min  c^T x  s.t. A x = b,  D x <= e
       Block-diagonal D (subproblems) + linking A. Reformulate by
       expressing x as a convex combination of subproblem extreme
       points; master picks weights via column generation.

     • LAGRANGIAN RELAXATION
         min  c^T x  s.t. A x <= b,  x ∈ S (easy)
       Dualize Ax ≤ b: L(λ) = min_x c^T x + λ^T(Ax - b).
       Maximize L(λ) over λ ≥ 0 via subgradient ascent.
       Lower bound on the original min.

   Each tab shows: master/subproblem split, bound progression,
   per-iteration table.
   ============================================================ */

// ============================================================
// Pre-computed iteration histories
// (Shows the qualitative shape — students can feed real solvers
// to confirm.)
// ============================================================
const BENDERS_ITERS = [
  { it: 1, master: 18.0, sub: 24.5, gap: 6.5, action: "x=(1,0,0); y-LP gives optimality cut π·B y >= ..." },
  { it: 2, master: 21.2, sub: 24.5, gap: 3.3, action: "x=(1,1,0); y-LP feasible; add cut tightening master" },
  { it: 3, master: 23.4, sub: 23.7, gap: 0.3, action: "x=(0,1,1); near-converged" },
  { it: 4, master: 23.7, sub: 23.7, gap: 0.0, action: "x=(0,1,1); cut active, master = sub → STOP" },
];

const DW_ITERS = [
  { it: 1, master: 12.0, sub: 18.5, gap: 6.5, action: "Master = -∞; pricing finds extreme point of block 1, λ_1 >= 0" },
  { it: 2, master: 16.4, sub: 16.8, gap: 0.4, action: "Add column from block 2; master moves toward optimum" },
  { it: 3, master: 16.7, sub: 16.8, gap: 0.1, action: "Reduced cost of new column ≈ 0 — close to convergence" },
  { it: 4, master: 16.8, sub: 16.8, gap: 0.0, action: "All reduced costs ≥ 0 → STOP" },
];

const LAG_ITERS = [
  { it: 1, lambda: 0.0, lower: 12.0, action: "L(0) — solves restricted to S; loose bound" },
  { it: 2, lambda: 0.5, lower: 14.6, action: "Subgradient step: λ ← λ + α(Ax* − b), α=0.5" },
  { it: 3, lambda: 0.95, lower: 15.9, action: "Continue ascent" },
  { it: 4, lambda: 1.32, lower: 16.5, action: "Step-size halved (α=0.25); still climbing" },
  { it: 5, lambda: 1.55, lower: 16.7, action: "Diminishing returns; near LP relaxation bound" },
  { it: 6, lambda: 1.61, lower: 16.74, action: "Plateau — stop or switch to bundle method" },
];
const LAG_LP_BOUND = 16.8;
const LAG_OPT = 17.0;

// ============================================================
// Main component
// ============================================================
export default function DecompositionDemo() {
  const [tab, setTab] = useState("benders");
  return (
    <div style={{ maxWidth: 1280, margin: "0 auto", padding: "32px 24px 80px" }}>
      <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 4 }}>
        IP Decomposition: Benders, Dantzig-Wolfe, Lagrangian
      </h1>
      <p style={{ color: "#666", marginBottom: 18, maxWidth: 880 }}>
        Three classical ways to break a hard MIP into easier
        sub-pieces. Each one trades 'one big problem' for 'a master + a
        sequence of subproblems', with iterative communication between
        them. Switch tabs to compare master/subproblem splits and
        bound-progression patterns.
      </p>

      <div style={{ display: "flex", gap: 6, marginBottom: 14 }}>
        {[
          ["benders", "Benders", "#0b3da0"],
          ["dw", "Dantzig–Wolfe", "#c8311c"],
          ["lag", "Lagrangian", "#1f4e3d"],
        ].map(([k, label, color]) => (
          <button
            key={k}
            onClick={() => setTab(k)}
            style={{
              padding: "8px 14px",
              border: "1px solid #ccc",
              borderRadius: 6,
              cursor: "pointer",
              background: tab === k ? color : "#fff",
              color: tab === k ? "#fff" : "#222",
              fontWeight: tab === k ? 700 : 500,
            }}
          >
            {label}
          </button>
        ))}
      </div>

      {tab === "benders" && <Benders />}
      {tab === "dw" && <DantzigWolfe />}
      {tab === "lag" && <Lagrangian />}

      <PedagogicalNotes />
    </div>
  );
}

// ============================================================
// Benders
// ============================================================
function Benders() {
  const [k, setK] = useState(0);
  const view = BENDERS_ITERS.slice(0, k + 1);
  return (
    <>
      <div style={problemBox}>
        <Tex block>
          {String.raw`\max\;\; c^T x + d^T y \;\;\;\;\text{s.t.}\;\; A x + B y \le b,\;\; x \in X \subseteq \mathbb{Z}^n,\;\; y \ge 0`}
        </Tex>
        <div style={{ fontSize: 13, color: "#444", marginTop: 6 }}>
          Idea: project out the easy block <Tex>{`y`}</Tex>. For each fixed
          <Tex>{` \\hat x`}</Tex> the y-LP is{" "}
          <Tex>{String.raw`\max\, d^T y\;\text{s.t.}\;B y \le b - A\hat x,\, y \ge 0`}</Tex>.
          Its dual is{" "}
          <Tex>{String.raw`\min\, \pi^T (b - A\hat x)\;\text{s.t.}\;\pi^T B \ge d,\,\pi \ge 0`}</Tex>.
          The DUAL extreme rays/points generate cuts for the master:
        </div>
        <Tex block>
          {String.raw`\text{master:}\;\; \max\, c^T x + \theta\;\;\text{s.t.}\;\; \theta \le \pi_k^T(b - A x)\;\forall k,\;\; \pi_r^T(b - A x) \ge 0 \;\forall r,\;\; x \in X.`}
        </Tex>
      </div>

      <Stepper k={k} setK={setK} max={BENDERS_ITERS.length - 1} />

      <BoundChart
        rows={view}
        upperLabel="Master (UB)"
        lowerLabel="Subproblem (best LB)"
        upperKey="master"
        lowerKey="sub"
        upperColor="#0b3da0"
        lowerColor="#c8311c"
      />
      <IterTable
        rows={view}
        cols={[
          { key: "it", label: "iter" },
          { key: "master", label: "Master UB" },
          { key: "sub", label: "Sub LB" },
          { key: "gap", label: "gap" },
          { key: "action", label: "action" },
        ]}
      />
      <CodeBlock code={`# Pseudo-Benders (PuLP)
master = LpProblem("master", LpMaximize)
x = ...; theta = LpVariable("theta")
master += c @ x + theta
while True:
    master.solve()
    x_hat = [v.value() for v in x]
    sub = build_dual_LP(x_hat)
    sub.solve()
    if sub.status == 'unbounded':
        # Feasibility cut
        ray = sub.dual_ray()
        master += ray @ (b - A @ x) >= 0
    else:
        if theta.value() >= sub.objective_value() - 1e-6:
            break  # converged
        pi = sub.dual_solution()
        master += theta <= pi @ (b - A @ x)
return x_hat, theta.value()`}
      />
    </>
  );
}

// ============================================================
// Dantzig-Wolfe
// ============================================================
function DantzigWolfe() {
  const [k, setK] = useState(0);
  const view = DW_ITERS.slice(0, k + 1);
  return (
    <>
      <div style={problemBox}>
        <Tex block>
          {String.raw`\min\;\; c^T x \;\;\;\;\text{s.t.}\;\; A x = b\;\;(\text{linking}),\;\; D x \le e\;\;(\text{block-diagonal}),\;\; x \ge 0`}
        </Tex>
        <div style={{ fontSize: 13, color: "#444", marginTop: 6 }}>
          The block constraints define a polytope{" "}
          <Tex>{`P = \\{x : Dx \\le e\\}`}</Tex>, factorized as{" "}
          <Tex>{`P = P_1 \\times P_2 \\times \\ldots \\times P_K`}</Tex>.
          Express{" "}
          <Tex>{String.raw`x = \sum_k \lambda_k v_k`}</Tex>, where{" "}
          <Tex>{`v_k`}</Tex> are extreme points of <Tex>{`P`}</Tex>.
          Master:
        </div>
        <Tex block>
          {String.raw`\min\;\; \sum_k (c^T v_k) \lambda_k \;\;\text{s.t.}\;\; \sum_k (A v_k) \lambda_k = b,\;\; \sum_k \lambda_k = 1,\;\; \lambda_k \ge 0`}
        </Tex>
        <div style={{ fontSize: 13, color: "#444", marginTop: 6 }}>
          Subproblem prices new columns:{" "}
          <Tex>{String.raw`\min_{v \in P_k} (c - \pi^T A)^T v`}</Tex>.
          Add the new column if its reduced cost is negative.
        </div>
      </div>

      <Stepper k={k} setK={setK} max={DW_ITERS.length - 1} />

      <BoundChart
        rows={view}
        upperLabel="Sub UB (overestimate)"
        lowerLabel="Master LB"
        upperKey="sub"
        lowerKey="master"
        upperColor="#c8311c"
        lowerColor="#0b3da0"
        invert
      />
      <IterTable
        rows={view}
        cols={[
          { key: "it", label: "iter" },
          { key: "master", label: "Master obj" },
          { key: "sub", label: "Pricing UB" },
          { key: "gap", label: "gap" },
          { key: "action", label: "action" },
        ]}
      />
      <CodeBlock code={`# Pseudo-Dantzig-Wolfe (PuLP-ish)
master = LpProblem("RMP", LpMinimize)
lam = []
# initial extreme points (v_1, ..., v_K)
add_columns(master, initial_extreme_points)

while True:
    master.solve()
    pi  = duals_on_linking_constraints(master)
    sigma = dual_on_convexity_constraint(master)
    # Pricing — solve K independent subproblems
    new_cols = []
    for k in range(K):
        sub_k = LpProblem(f"sub_{k}", LpMinimize)
        sub_k += (c - pi @ A) @ x_k - sigma
        sub_k += D_k @ x_k <= e_k
        sub_k.solve()
        if sub_k.objective_value() < -1e-6:
            new_cols.append(extract_solution(sub_k))
    if not new_cols:
        break       # all reduced costs >= 0
    add_columns(master, new_cols)`}
      />
    </>
  );
}

// ============================================================
// Lagrangian
// ============================================================
function Lagrangian() {
  const [k, setK] = useState(0);
  const view = LAG_ITERS.slice(0, k + 1);
  return (
    <>
      <div style={problemBox}>
        <Tex block>
          {String.raw`\min\;\; c^T x \;\;\;\;\text{s.t.}\;\; A x \le b\;\;(\text{hard}),\;\; x \in S\;\;(\text{easy})`}
        </Tex>
        <div style={{ fontSize: 13, color: "#444", marginTop: 6 }}>
          Dualize the hard constraint:
          <Tex block>
            {String.raw`L(\lambda) \;=\; \min_{x \in S}\; c^T x + \lambda^T (A x - b)`}
          </Tex>
          The Lagrangian dual{" "}
          <Tex>{String.raw`\;\max_{\lambda \ge 0}\,L(\lambda)\;`}</Tex> is a
          concave optimization problem (piecewise linear in{" "}
          <Tex>{`\\lambda`}</Tex>), maximized by subgradient ascent:
          <Tex block>
            {String.raw`\lambda_{k+1} = [\lambda_k + \alpha_k\,(A x_k - b)]_+`}
          </Tex>
          where <Tex>{`x_k`}</Tex> is the minimizer of the inner problem and{" "}
          <Tex>{String.raw`\alpha_k`}</Tex> is a step size. The dual is a
          LOWER BOUND for the primal min (weak duality).
        </div>
      </div>

      <Stepper k={k} setK={setK} max={LAG_ITERS.length - 1} />

      <LagrangianChart history={view} />
      <IterTable
        rows={view}
        cols={[
          { key: "it", label: "iter" },
          { key: "lambda", label: "λ" },
          { key: "lower", label: "L(λ)" },
          { key: "action", label: "action" },
        ]}
      />
      <div style={{ marginTop: 8, padding: "10px 14px", background: "#fff8e1", border: "1px solid #f5d68d", borderRadius: 6, fontSize: 13 }}>
        Best Lagrangian bound here is <Tex>{`${LAG_ITERS[LAG_ITERS.length - 1].lower}`}</Tex>.
        The LP-relaxation bound is{" "}
        <Tex>{`${LAG_LP_BOUND}`}</Tex>; the IP optimum is{" "}
        <Tex>{`${LAG_OPT}`}</Tex>. The 'duality gap' is the difference
        between the Lagrangian bound and the IP optimum.
      </div>
      <CodeBlock code={`# Pseudo-Lagrangian relaxation with subgradient ascent
lam = np.zeros(m)            # one multiplier per hard constraint
alpha = 1.0
best_lower = -np.inf

for k in range(MAX_ITER):
    # Inner problem: minimize over the easy set S
    x = solve_easy_subproblem(c + lam @ A, S)
    val = (c @ x) + lam @ (A @ x - b)
    best_lower = max(best_lower, val)

    # Subgradient = (A x - b) — direction to make the constraint tighter
    g = A @ x - b
    # Polyak step (or harmonic 1/k):
    alpha_k = (best_known_UB - val) / (np.linalg.norm(g)**2)
    lam = np.maximum(0, lam + alpha_k * g)

    if alpha_k < 1e-6: break
return best_lower
`}
      />
    </>
  );
}

// ============================================================
// Shared widgets
// ============================================================
function Stepper({ k, setK, max }) {
  return (
    <div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 14 }}>
      <button onClick={() => setK(Math.min(max, k + 1))} disabled={k >= max} style={btnPrimary}>
        <StepForward size={16} /> Next iteration
      </button>
      <button onClick={() => setK(0)} style={btn}>
        <RotateCcw size={16} /> Reset
      </button>
      <span style={{ fontSize: 12, fontFamily: "monospace", color: "#666" }}>
        iter {k + 1} / {max + 1}
      </span>
    </div>
  );
}

function BoundChart({ rows, upperKey, lowerKey, upperLabel, lowerLabel, upperColor, lowerColor, invert }) {
  const W = 720, H = 220, padL = 60, padR = 16, padT = 14, padB = 30;
  const cw = W - padL - padR, ch = H - padT - padB;
  const N = rows.length;
  if (N === 0) return null;
  const upperVals = rows.map((r) => r[upperKey]);
  const lowerVals = rows.map((r) => r[lowerKey]);
  const all = [...upperVals, ...lowerVals];
  const yMin = Math.min(...all);
  const yMax = Math.max(...all);
  const xs = (i) => padL + (i / Math.max(1, N - 1)) * cw;
  const ys = (v) => padT + (1 - (v - yMin) / Math.max(1e-9, yMax - yMin)) * ch;

  return (
    <div style={panel}>
      <div style={{ fontFamily: "monospace", fontSize: 11, color: "#888", marginBottom: 4 }}>
        bound progression
      </div>
      <svg width={W} height={H}>
        <line x1={padL} y1={padT + ch} x2={padL + cw} y2={padT + ch} stroke="#bbb" />
        <line x1={padL} y1={padT} x2={padL} y2={padT + ch} stroke="#bbb" />
        {/* upper */}
        <polyline
          points={upperVals.map((v, i) => `${xs(i)},${ys(v)}`).join(" ")}
          fill="none"
          stroke={upperColor}
          strokeWidth={2}
        />
        {upperVals.map((v, i) => (
          <circle key={i} cx={xs(i)} cy={ys(v)} r={4} fill={upperColor} />
        ))}
        {/* lower */}
        <polyline
          points={lowerVals.map((v, i) => `${xs(i)},${ys(v)}`).join(" ")}
          fill="none"
          stroke={lowerColor}
          strokeWidth={2}
        />
        {lowerVals.map((v, i) => (
          <circle key={i} cx={xs(i)} cy={ys(v)} r={4} fill={lowerColor} />
        ))}
        {/* gap fill */}
        {upperVals.map((u, i) => {
          if (i === 0) return null;
          const u0 = upperVals[i - 1], u1 = u;
          const l0 = lowerVals[i - 1], l1 = lowerVals[i];
          const path = `M ${xs(i - 1)} ${ys(u0)} L ${xs(i)} ${ys(u1)} L ${xs(i)} ${ys(l1)} L ${xs(i - 1)} ${ys(l0)} Z`;
          return <path key={i} d={path} fill={upperColor + "11"} />;
        })}
        {/* y labels */}
        <text x={padL - 6} y={padT + 4} textAnchor="end" fontSize={10} fontFamily="monospace" fill="#666">
          {yMax.toFixed(2)}
        </text>
        <text x={padL - 6} y={padT + ch} textAnchor="end" fontSize={10} fontFamily="monospace" fill="#666">
          {yMin.toFixed(2)}
        </text>
        {/* legend */}
        <g transform={`translate(${padL + 12}, ${padT + 4})`}>
          <line x1={0} y1={6} x2={14} y2={6} stroke={upperColor} strokeWidth={2} />
          <text x={18} y={10} fontSize={10}>{upperLabel}</text>
          <line x1={130} y1={6} x2={144} y2={6} stroke={lowerColor} strokeWidth={2} />
          <text x={148} y={10} fontSize={10}>{lowerLabel}</text>
        </g>
      </svg>
    </div>
  );
}

function LagrangianChart({ history }) {
  const W = 720, H = 240, padL = 60, padR = 16, padT = 14, padB = 30;
  const cw = W - padL - padR, ch = H - padT - padB;
  if (history.length === 0) return null;

  // x-axis: lambda
  const lams = history.map((r) => r.lambda);
  const lows = history.map((r) => r.lower);
  const xMin = 0, xMax = Math.max(2, ...lams) * 1.1;
  const yMin = Math.min(...lows, 0);
  const yMax = Math.max(LAG_OPT * 1.05, ...lows);
  const xs = (v) => padL + ((v - xMin) / (xMax - xMin)) * cw;
  const ys = (v) => padT + (1 - (v - yMin) / Math.max(1e-9, yMax - yMin)) * ch;

  // Sample L(λ) curve — piecewise linear concave
  // Use the historical points + extend; pretend the dual is piecewise linear
  // through the visited points.
  const dualCurve = [...history].sort((a, b) => a.lambda - b.lambda);
  const dualPath = dualCurve.map((p) => `${xs(p.lambda)},${ys(p.lower)}`).join(" ");

  return (
    <div style={panel}>
      <div style={{ fontFamily: "monospace", fontSize: 11, color: "#888", marginBottom: 4 }}>
        Lagrangian dual function L(λ) — concave, piecewise linear
      </div>
      <svg width={W} height={H}>
        <line x1={padL} y1={padT + ch} x2={padL + cw} y2={padT + ch} stroke="#bbb" />
        <line x1={padL} y1={padT} x2={padL} y2={padT + ch} stroke="#bbb" />
        {/* IP optimum (target) */}
        <line x1={padL} y1={ys(LAG_OPT)} x2={padL + cw} y2={ys(LAG_OPT)} stroke="#c8311c" strokeWidth={2} strokeDasharray="6,4" />
        <text x={padL + cw - 6} y={ys(LAG_OPT) - 4} textAnchor="end" fontSize={10} fill="#c8311c">
          IP opt = {LAG_OPT}
        </text>
        {/* LP bound */}
        <line x1={padL} y1={ys(LAG_LP_BOUND)} x2={padL + cw} y2={ys(LAG_LP_BOUND)} stroke="#0b3da0" strokeWidth={1.5} strokeDasharray="3,3" />
        <text x={padL + cw - 6} y={ys(LAG_LP_BOUND) + 12} textAnchor="end" fontSize={10} fill="#0b3da0">
          LP bound = {LAG_LP_BOUND}
        </text>
        {/* dual curve */}
        <polyline points={dualPath} fill="none" stroke="#1f4e3d" strokeWidth={2.5} />
        {/* iterate path */}
        <polyline
          points={history.map((p) => `${xs(p.lambda)},${ys(p.lower)}`).join(" ")}
          fill="none"
          stroke="#7a3da0"
          strokeWidth={1.5}
          strokeDasharray="4,2"
        />
        {history.map((p, i) => (
          <g key={i}>
            <circle cx={xs(p.lambda)} cy={ys(p.lower)} r={i === history.length - 1 ? 6 : 4} fill={i === history.length - 1 ? "#c8311c" : "#1f4e3d"} stroke="#fff" strokeWidth={1.5} />
            <text x={xs(p.lambda) + 6} y={ys(p.lower) - 6} fontSize={9} fontFamily="monospace" fill="#444">
              k={p.it}
            </text>
          </g>
        ))}
        {/* axis labels */}
        <text x={padL + cw / 2} y={H - 6} textAnchor="middle" fontSize={11} fontFamily="monospace" fill="#444">
          λ
        </text>
        <text x={20} y={padT + ch / 2} textAnchor="middle" fontSize={11} fontFamily="monospace" fill="#444" transform={`rotate(-90, 20, ${padT + ch / 2})`}>
          L(λ)
        </text>
      </svg>
    </div>
  );
}

function IterTable({ rows, cols }) {
  return (
    <div style={{ ...panel, marginTop: 14 }}>
      <table style={{ width: "100%", fontFamily: "monospace", fontSize: 12, borderCollapse: "collapse" }}>
        <thead>
          <tr style={{ borderBottom: "1px solid #ccc" }}>
            {cols.map((c) => (
              <th key={c.key} style={{ padding: 4, textAlign: c.key === "action" ? "left" : "right" }}>
                {c.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={i} style={{ borderBottom: "1px dotted #eee" }}>
              {cols.map((c) => (
                <td key={c.key} style={{ padding: 4, textAlign: c.key === "action" ? "left" : "right" }}>
                  {typeof r[c.key] === "number" ? r[c.key].toFixed(3) : r[c.key]}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function CodeBlock({ code }) {
  return (
    <pre
      style={{
        marginTop: 14,
        background: "#1f1d1a",
        color: "#e8e2d4",
        padding: 14,
        borderRadius: 8,
        fontSize: 12,
        fontFamily: "'JetBrains Mono', Menlo, monospace",
        lineHeight: 1.55,
        whiteSpace: "pre",
        overflowX: "auto",
      }}
    >
      {code}
    </pre>
  );
}

// ============================================================
// Pedagogical notes
// ============================================================
function PedagogicalNotes() {
  return (
    <div style={{ marginTop: 28, padding: 16, background: "#fff8e1", borderRadius: 10, border: "1px solid #f5d68d" }}>
      <div style={{ fontWeight: 700, marginBottom: 6 }}>
        <Terminal size={14} style={{ verticalAlign: "middle", marginRight: 6 }} />
        Notes for class
      </div>
      <ul style={{ margin: 0, paddingLeft: 22, lineHeight: 1.6, fontSize: 14, color: "#3d2f00" }}>
        <li>
          <b>When to use Benders.</b> Two-stage stochastic programming
          (binary first-stage, continuous recourse). Network design with
          embedded LP. Anytime a small set of integer decisions
          determines a much larger LP.
        </li>
        <li>
          <b>When to use Dantzig-Wolfe / column generation.</b>{" "}
          Block-diagonal structure with a small linking system. Vehicle
          routing, crew scheduling, cutting stock — the master prices
          out millions of potential 'patterns' on demand.
        </li>
        <li>
          <b>When to use Lagrangian.</b> Hard 'coupling' constraints, easy
          subproblem when they're removed. Knapsack with side constraints.
          Generalized assignment. Multi-commodity flow.
        </li>
        <li>
          <b>Integrality gap.</b> Both Benders and DW in their PURE form
          give the LP relaxation bound — same as just solving the LP.
          Strength comes from <b>cuts in the master</b>{" "}
          (Benders) or <b>integer subproblem</b> (DW). For Lagrangian,
          if the easy set <Tex>{`S`}</Tex> has the integrality property,
          the bound equals the LP. Otherwise it's stronger.
        </li>
        <li>
          <b>Branch-and-price.</b> Dantzig-Wolfe + branch-and-bound. Each
          B&B node maintains its own column-generation master; branching
          rules must respect the column representation. Used in vehicle
          routing benchmarks.
        </li>
        <li>
          <b>Bundle methods.</b> The pure subgradient method for the
          Lagrangian dual is slow. Bundle methods (Kelley, level bundle,
          proximal bundle) keep a bundle of past subgradients and solve
          a small QP for the next iterate — much faster in practice.
        </li>
      </ul>
    </div>
  );
}

// ============================================================
// Style atoms
// ============================================================
const panel = {
  background: "#fafafa",
  border: "1px solid #ddd",
  borderRadius: 8,
  padding: 12,
};
const problemBox = {
  marginBottom: 14,
  padding: "12px 16px",
  background: "#f6f4ee",
  border: "1px solid #ece8dd",
  borderRadius: 8,
};
const btn = {
  display: "inline-flex",
  alignItems: "center",
  gap: 6,
  padding: "6px 12px",
  borderRadius: 6,
  border: "1px solid #ccc",
  background: "#f7f7f7",
  cursor: "pointer",
  fontWeight: 500,
  fontSize: 13,
};
const btnPrimary = { ...btn, background: "#111", color: "#fff", border: "1px solid #111" };
